version: 0.2

env:
  git-credential-helper: yes
  
phases:
  pre_build:
    commands: 
      - git submodule update --init --recursive
 
 artifacts:
  files:
    - '**/*'
   base-directory: peer-recognition
   name: deployment-build-artifacts
   discard-paths: no
