version: 0.2

env:
  git-credential-helper: yes
  
phases:
  pre_build:
    commands: 
      - git submodule init
      - git submodule update --init --recursive
  build:
    commands:
      - cd peer-recognition-backend
      - npm install
      - npm run build
      - cd ..
      - cd peer-recognition
      - npm install
      - cd .. 
artifacts:
  files:
    - 'dist/**/*'
  name: deployment-build-artifacts
  discard-paths: no
