version: 0.2

env:
  git-credential-helper: yes
  
phases:
#   pre_build:
#     commands: 
#       - git submodule init
#       - git submodule update --init --recursive
 
artifacts:
  files:
    - '**/*'
  name: deployment-build-artifacts
  discard-paths: no
