# This is a basic workflow to help you get started with Actions

name: Deployment-CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodule: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - name: Docker Experimental Status
        run: |
          docker version -f '{{.Server.Experimental}}'
      - name: Turn on Experimental Docker Features
        run: |
          echo $'{\n  "experimental": true,\n  "features": {\n    "buildkit": true\n  }\n}' | sudo tee /etc/docker/daemon.json
          mkdir -p ~/.docker
          echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
          sudo service docker restart
      - name: Docker Experimental Status
        run: |
          docker version -f '{{.Server.Experimental}}'
      - name: install docker app
        run: |
          export OSTYPE="$(uname | tr A-Z a-z)" 
          curl -fsSL --output "/tmp/docker-app-${OSTYPE}.tar.gz" "https://github.com/docker/app/releases/download/v0.8.0/docker-app-${OSTYPE}.tar.gz"
          tar xf "/tmp/docker-app-${OSTYPE}.tar.gz" -C /tmp/
          mkdir -p ~/.docker/cli-plugins && cp "/tmp/docker-app-plugin-${OSTYPE}" ~/.docker/cli-plugins/docker-app
      - run: docker swarm init
      - run: docker app init peer-recognition-full-stack --compose-file docker-compose.yml --single-file
      - run: ls
      - run: cat peer-recognition-full-stack.dockerapp
      - run: docker app inspect peer-recognition-full-stack.dockerapp
      - run: docker app validate peer-recognition-full-stack.dockerapp
      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker app install peer-recognition-full-stack.dockerapp --name ghcr.io/benedict-scrumberbatch/peer-recognition-full-stack-localhost-docker-image:latest
      - run: docker app status ghcr.io/benedict-scrumberbatch/peer-recognition-full-stack-localhost-docker-image:latest
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: Benedict-Scrumberbatch
#           password: ${{ secrets.GITHUB_TOKEN }}
 
      - run: docker app push ghcr.io/benedict-scrumberbatch/peer-recognition-full-stack-localhost-docker-image:latest
